export default {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  SET_TODOS: "SET_TODOS",
  LOAD_TODOS: "LOAD_TODOS",
  SET_INPUT_CONTENT: "SET_INPUT_CONTENT",
  SET_ID: "SET_ID",
  RESET_INPUT: "RESET_INPUT",
};
